pdi:
  image: image_cenipa/pdi
  links:
     - biserver:edw_biserver
     - postgres-draw:edw_db
  volumes:
    - /data/stage:/tmp/stage
  environment:
    - PGHOST=postgres-draw
    - PGUSER=pgadmin
    - PGPASSWORD=pgadmin.
    - PENTAHO_DI_JAVA_OPTIONS=-Xmx2014m -XX:MaxPermSize=256m
  stdin_open: true
  tty: true
biserver:
  image: image_cenipa/biserver
  ports:
    - "9092:8080"
  links:
    - postgres-draw:edw_db
  environment:
    - PGUSER=pgadmin
    - PGPASSWORD=pgadmin.
    - INSTALL_PLUGIN=saiku
    - CUSTOM_LAYOUT=y
  stdin_open: true
  tty: true
#db:
#  image: postgres:9.3
#  environment:
#    - POSTGRES_USER=pgadmin
#   - POSTGRES_PASSWORD=pgadmin.
#  ports:
#    - "5432:5432"
  stdin_open: false
  tty: true
